package meta

import (
	"hit.edu/framework/pkg/apimachinery/runtime"
	"hit.edu/framework/pkg/apimachinery/runtime/schema"
	"hit.edu/framework/pkg/component-base/logs"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
)

const GroupName = "meta"

var SchemeGroupVersion = schema.GroupVersion{Group: GroupName, Version: "v1"}

var Unversioned = schema.GroupVersion{Group: "", Version: "v1"}

// WatchEventKind is name reserved for serializing watch events.
const WatchEventKind = "WatchEvent"

var (
	// localSchemeBuilder is used to make compiler happy for autogenerated
	// conversions. However, it's not used.
	schemeBuilder      runtime.SchemeBuilder
	localSchemeBuilder = &schemeBuilder
)

var scheme = runtime.NewScheme()

//var ParameterCodec = runtime.NewParameterCodec(scheme)

var optionsTypes = []runtime.Object{
	&ListOptions{},
	&GetOptions{},
	&DeleteOptions{},
	&CreateOptions{},
	&UpdateOptions{},
	&PatchOptions{},
}

// AddToGroupVersion registers common meta types into schemas.
func AddToGroupVersion(scheme *runtime.Scheme, groupVersion schema.GroupVersion) {
	scheme.AddKnownTypeWithName(groupVersion.WithKind(WatchEventKind), &WatchEvent{})
	scheme.AddKnownTypeWithName(
		schema.GroupVersion{Group: groupVersion.Group, Version: runtime.APIVersionInternal}.WithKind(WatchEventKind),
		&InternalEvent{},
	)
	// Supports legacy code paths, most callers should use metav1.ParameterCodec for now
	scheme.AddKnownTypes(groupVersion, optionsTypes...)
	// Register Unversioned types under their own special group
	scheme.AddUnversionedTypes(Unversioned,
		&Status{},
		//&APIVersions{},
		//&APIGroupList{},
		//&APIGroup{},
		&APIResourceList{},
	)
}

// AddMetaToScheme registers base meta types into schemas.
func AddMetaToScheme(scheme *runtime.Scheme) error {
	scheme.AddKnownTypes(SchemeGroupVersion)
	return nil
}

// AddTypes 注册已知meta类型
// TODO:注册WatchEvent类型
func AddTypes(scheme *runtime.Scheme) error {
	//TODO:替换成自己的watchEvent
	scheme.AddKnownTypeWithName(SchemeGroupVersion.WithKind(WatchEventKind), &WatchEvent{})
	scheme.AddKnownTypeWithName(
		schema.GroupVersion{Group: SchemeGroupVersion.Group, Version: runtime.APIVersionInternal}.WithKind(WatchEventKind),
		&InternalEvent{},
	)
	scheme.AddKnownTypes(SchemeGroupVersion, &Status{})
	scheme.AddKnownTypes(
		schema.GroupVersion{Group: SchemeGroupVersion.Group, Version: runtime.APIVersionInternal},
		&Status{},
	)

	scheme.AddKnownTypes(SchemeGroupVersion, optionsTypes...)
	scheme.AddUnversionedTypes(SchemeGroupVersion, optionsTypes...)
	if err := RegisterConversions(scheme); err != nil {
		logs.Info(err)
	}
	return nil
}

func init() {
	scheme.AddUnversionedTypes(SchemeGroupVersion, optionsTypes...)
	utilruntime.Must(AddMetaToScheme(scheme))
}
