package listers

import (
	"hit.edu/framework/pkg/apimachinery/runtime"
	"hit.edu/framework/pkg/apimachinery/runtime/schema"
	"hit.edu/framework/pkg/client-go/tools/cache"
)

// From K8s
type ResourceIndexer[T runtime.Object] struct {
	indexer   cache.Indexer
	resource  schema.GroupResource
	namespace string // empty for non-namespaced types
}

// New returns a new instance of a lister (resource indexer) wrapping the given indexer and resource for the specified type.
// This is intended for use by listers (generated by lister-gen) only.
func New[T runtime.Object](indexer cache.Indexer, resource schema.GroupResource) ResourceIndexer[T] {
	return ResourceIndexer[T]{indexer: indexer, resource: resource}
}

// NewNamespaced returns a new instance of a namespaced lister (resource indexer) wrapping the given parent and namespace for the specified type.
// This is intended for use by listers (generated by lister-gen) only.
func NewNamespaced[T runtime.Object](parent ResourceIndexer[T], namespace string) ResourceIndexer[T] {
	return ResourceIndexer[T]{indexer: parent.indexer, resource: parent.resource, namespace: namespace}
}

// List lists all resources in the indexer matching the given selector.
// TODO: 完善该逻辑
// TODO: 增加Namespace支持
func (l ResourceIndexer[T]) List() (ret []T, err error) {
	// ListAllByNamespace reverts to ListAll on empty namespaces
	//err = cache.ListAllByNamespace(l.indexer, l.namespace, selector, func(m interface{}) {
	//	ret = append(ret, m.(T))
	//})
	return ret, err
}

//
//// Get retrieves the resource from the index for a given name.
//func (l ResourceIndexer[T]) Get(name string) (T, error) {
//	var key string
//	if l.namespace == "" {
//		key = name
//	} else {
//		key = l.namespace + "/" + name
//	}
//	obj, exists, err := l.indexer.GetByKey(key)
//	if err != nil {
//		return *new(T), err
//	}
//	if !exists {
//		return *new(T), errors.NewNotFound(l.resource, name)
//	}
//	return obj.(T), nil
//}
