# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\"(\n\x06Result\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x11\n\tstateCode\x18\x02 \x01(\x03\"M\n\tAPPStatus\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x11\n\tstateCode\x18\x02 \x01(\x03\x12 \n\tlifecycle\x18\x03 \x01(\x0e\x32\r.AppLifecycle\";\n\x04\x44\x61ta\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x04type\x18\x02 \x01(\x0e\x32\t.DataType\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"\x19\n\nInitIntent\x12\x0b\n\x03\x61pp\x18\x01 \x01(\t\"\x1a\n\x0bStartIntent\x12\x0b\n\x03\x61pp\x18\x01 \x01(\t\"\x1c\n\rRestartIntent\x12\x0b\n\x03\x61pp\x18\x01 \x01(\t\"\x19\n\nStopIntent\x12\x0b\n\x03\x61pp\x18\x01 \x01(\t\"\x1e\n\x0fGetStatusIntent\x12\x0b\n\x03\x61pp\x18\x01 \x01(\t\"\x1a\n\x0bStoreIntent\x12\x0b\n\x03\x61pp\x18\x01 \x01(\t\"\x1c\n\rRestoreIntent\x12\x0b\n\x03\x61pp\x18\x01 \x01(\t*\x94\x01\n\x0c\x41ppLifecycle\x12\x08\n\x04INIT\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\x12\r\n\tCOMPLETED\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x12\x0b\n\x07STOPPED\x10\x05\x12\x0e\n\nTERMINATED\x10\x06\x12\x0b\n\x07STORING\x10\x07\x12\r\n\tMIGRATING\x10\x08\x12\r\n\tRESTORING\x10\t*\x1e\n\x08\x44\x61taType\x12\x08\n\x04\x44\x41TA\x10\x00\x12\x08\n\x04HTTP\x10\x01\x32\x89\x02\n\nTaskIntent\x12\x1e\n\x04init\x12\x0b.InitIntent\x1a\x07.Result\"\x00\x12 \n\x05start\x12\x0c.StartIntent\x1a\x07.Result\"\x00\x12$\n\x07restart\x12\x0e.RestartIntent\x1a\x07.Result\"\x00\x12\x1e\n\x04stop\x12\x0b.StopIntent\x1a\x07.Result\"\x00\x12+\n\tgetStatus\x12\x10.GetStatusIntent\x1a\n.APPStatus\"\x00\x12 \n\x05store\x12\x0c.StoreIntent\x1a\x07.Result\"\x00\x12$\n\x07restore\x12\x0e.RestoreIntent\x1a\x07.Result\"\x00\x42\x0bZ\t.;serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t.;service'
  _globals['_APPLIFECYCLE']._serialized_start=399
  _globals['_APPLIFECYCLE']._serialized_end=547
  _globals['_DATATYPE']._serialized_start=549
  _globals['_DATATYPE']._serialized_end=579
  _globals['_RESULT']._serialized_start=14
  _globals['_RESULT']._serialized_end=54
  _globals['_APPSTATUS']._serialized_start=56
  _globals['_APPSTATUS']._serialized_end=133
  _globals['_DATA']._serialized_start=135
  _globals['_DATA']._serialized_end=194
  _globals['_INITINTENT']._serialized_start=196
  _globals['_INITINTENT']._serialized_end=221
  _globals['_STARTINTENT']._serialized_start=223
  _globals['_STARTINTENT']._serialized_end=249
  _globals['_RESTARTINTENT']._serialized_start=251
  _globals['_RESTARTINTENT']._serialized_end=279
  _globals['_STOPINTENT']._serialized_start=281
  _globals['_STOPINTENT']._serialized_end=306
  _globals['_GETSTATUSINTENT']._serialized_start=308
  _globals['_GETSTATUSINTENT']._serialized_end=338
  _globals['_STOREINTENT']._serialized_start=340
  _globals['_STOREINTENT']._serialized_end=366
  _globals['_RESTOREINTENT']._serialized_start=368
  _globals['_RESTOREINTENT']._serialized_end=396
  _globals['_TASKINTENT']._serialized_start=582
  _globals['_TASKINTENT']._serialized_end=847
# @@protoc_insertion_point(module_scope)
