// 指定proto语言版本

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: taskIntent.taskproto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskIntent_Init_FullMethodName      = "/TaskIntent/init"
	TaskIntent_Start_FullMethodName     = "/TaskIntent/start"
	TaskIntent_Restart_FullMethodName   = "/TaskIntent/restart"
	TaskIntent_Stop_FullMethodName      = "/TaskIntent/stop"
	TaskIntent_GetStatus_FullMethodName = "/TaskIntent/getStatus"
	TaskIntent_Store_FullMethodName     = "/TaskIntent/store"
	TaskIntent_Restore_FullMethodName   = "/TaskIntent/restore"
)

// TaskIntentClient is the client API for TaskIntent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskIntentClient interface {
	// 应用
	Init(ctx context.Context, in *InitIntent, opts ...grpc.CallOption) (*Result, error)
	Start(ctx context.Context, in *StartIntent, opts ...grpc.CallOption) (*Result, error)
	Restart(ctx context.Context, in *RestartIntent, opts ...grpc.CallOption) (*Result, error)
	Stop(ctx context.Context, in *StopIntent, opts ...grpc.CallOption) (*Result, error)
	// 获取应用健康状态
	GetStatus(ctx context.Context, in *GetStatusIntent, opts ...grpc.CallOption) (*APPStatus, error)
	// 迁移相关
	//
	//	rpc migrate (MigateIntent) returns (Result) {}
	Store(ctx context.Context, in *StoreIntent, opts ...grpc.CallOption) (*Result, error)
	Restore(ctx context.Context, in *RestoreIntent, opts ...grpc.CallOption) (*Result, error)
}

type taskIntentClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskIntentClient(cc grpc.ClientConnInterface) TaskIntentClient {
	return &taskIntentClient{cc}
}

func (c *taskIntentClient) Init(ctx context.Context, in *InitIntent, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, TaskIntent_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskIntentClient) Start(ctx context.Context, in *StartIntent, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, TaskIntent_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskIntentClient) Restart(ctx context.Context, in *RestartIntent, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, TaskIntent_Restart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskIntentClient) Stop(ctx context.Context, in *StopIntent, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, TaskIntent_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskIntentClient) GetStatus(ctx context.Context, in *GetStatusIntent, opts ...grpc.CallOption) (*APPStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APPStatus)
	err := c.cc.Invoke(ctx, TaskIntent_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskIntentClient) Store(ctx context.Context, in *StoreIntent, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, TaskIntent_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskIntentClient) Restore(ctx context.Context, in *RestoreIntent, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, TaskIntent_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskIntentServer is the server API for TaskIntent service.
// All implementations must embed UnimplementedTaskIntentServer
// for forward compatibility.
type TaskIntentServer interface {
	// 应用
	Init(context.Context, *InitIntent) (*Result, error)
	Start(context.Context, *StartIntent) (*Result, error)
	Restart(context.Context, *RestartIntent) (*Result, error)
	Stop(context.Context, *StopIntent) (*Result, error)
	// 获取应用健康状态
	GetStatus(context.Context, *GetStatusIntent) (*APPStatus, error)
	// 迁移相关
	//
	//	rpc migrate (MigateIntent) returns (Result) {}
	Store(context.Context, *StoreIntent) (*Result, error)
	Restore(context.Context, *RestoreIntent) (*Result, error)
	mustEmbedUnimplementedTaskIntentServer()
}

// UnimplementedTaskIntentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskIntentServer struct{}

func (UnimplementedTaskIntentServer) Init(context.Context, *InitIntent) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedTaskIntentServer) Start(context.Context, *StartIntent) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedTaskIntentServer) Restart(context.Context, *RestartIntent) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedTaskIntentServer) Stop(context.Context, *StopIntent) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedTaskIntentServer) GetStatus(context.Context, *GetStatusIntent) (*APPStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedTaskIntentServer) Store(context.Context, *StoreIntent) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedTaskIntentServer) Restore(context.Context, *RestoreIntent) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedTaskIntentServer) mustEmbedUnimplementedTaskIntentServer() {}
func (UnimplementedTaskIntentServer) testEmbeddedByValue()                    {}

// UnsafeTaskIntentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskIntentServer will
// result in compilation errors.
type UnsafeTaskIntentServer interface {
	mustEmbedUnimplementedTaskIntentServer()
}

func RegisterTaskIntentServer(s grpc.ServiceRegistrar, srv TaskIntentServer) {
	// If the following call pancis, it indicates UnimplementedTaskIntentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskIntent_ServiceDesc, srv)
}

func _TaskIntent_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitIntent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskIntentServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskIntent_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskIntentServer).Init(ctx, req.(*InitIntent))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskIntent_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartIntent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskIntentServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskIntent_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskIntentServer).Start(ctx, req.(*StartIntent))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskIntent_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartIntent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskIntentServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskIntent_Restart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskIntentServer).Restart(ctx, req.(*RestartIntent))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskIntent_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopIntent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskIntentServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskIntent_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskIntentServer).Stop(ctx, req.(*StopIntent))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskIntent_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusIntent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskIntentServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskIntent_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskIntentServer).GetStatus(ctx, req.(*GetStatusIntent))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskIntent_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreIntent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskIntentServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskIntent_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskIntentServer).Store(ctx, req.(*StoreIntent))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskIntent_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreIntent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskIntentServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskIntent_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskIntentServer).Restore(ctx, req.(*RestoreIntent))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskIntent_ServiceDesc is the grpc.ServiceDesc for TaskIntent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskIntent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TaskIntent",
	HandlerType: (*TaskIntentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "init",
			Handler:    _TaskIntent_Init_Handler,
		},
		{
			MethodName: "start",
			Handler:    _TaskIntent_Start_Handler,
		},
		{
			MethodName: "restart",
			Handler:    _TaskIntent_Restart_Handler,
		},
		{
			MethodName: "stop",
			Handler:    _TaskIntent_Stop_Handler,
		},
		{
			MethodName: "getStatus",
			Handler:    _TaskIntent_GetStatus_Handler,
		},
		{
			MethodName: "store",
			Handler:    _TaskIntent_Store_Handler,
		},
		{
			MethodName: "restore",
			Handler:    _TaskIntent_Restore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "taskIntent.taskproto",
}
