// 指定proto语言版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v6.31.0--rc2
// source: runtimeIntent.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Constants
// 应用生命周期
type AppLifecycle int32

const (
	AppLifecycle_INIT       AppLifecycle = 0
	AppLifecycle_PENDING    AppLifecycle = 1
	AppLifecycle_RUNNING    AppLifecycle = 2
	AppLifecycle_COMPLETED  AppLifecycle = 3
	AppLifecycle_ERROR      AppLifecycle = 4
	AppLifecycle_STOPPED    AppLifecycle = 5
	AppLifecycle_TERMINATED AppLifecycle = 6
	AppLifecycle_STORING    AppLifecycle = 7
	AppLifecycle_MIGRATING  AppLifecycle = 8
	AppLifecycle_RESTORING  AppLifecycle = 9
)

// Enum value maps for AppLifecycle.
var (
	AppLifecycle_name = map[int32]string{
		0: "INIT",
		1: "PENDING",
		2: "RUNNING",
		3: "COMPLETED",
		4: "ERROR",
		5: "STOPPED",
		6: "TERMINATED",
		7: "STORING",
		8: "MIGRATING",
		9: "RESTORING",
	}
	AppLifecycle_value = map[string]int32{
		"INIT":       0,
		"PENDING":    1,
		"RUNNING":    2,
		"COMPLETED":  3,
		"ERROR":      4,
		"STOPPED":    5,
		"TERMINATED": 6,
		"STORING":    7,
		"MIGRATING":  8,
		"RESTORING":  9,
	}
)

func (x AppLifecycle) Enum() *AppLifecycle {
	p := new(AppLifecycle)
	*p = x
	return p
}

func (x AppLifecycle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppLifecycle) Descriptor() protoreflect.EnumDescriptor {
	return file_runtimeIntent_proto_enumTypes[0].Descriptor()
}

func (AppLifecycle) Type() protoreflect.EnumType {
	return &file_runtimeIntent_proto_enumTypes[0]
}

func (x AppLifecycle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppLifecycle.Descriptor instead.
func (AppLifecycle) EnumDescriptor() ([]byte, []int) {
	return file_runtimeIntent_proto_rawDescGZIP(), []int{0}
}

// 应用数据类型
type DataType int32

const (
	DataType_DATA DataType = 0
	DataType_HTTP DataType = 1 // ... 其他数据格式
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "DATA",
		1: "HTTP",
	}
	DataType_value = map[string]int32{
		"DATA": 0,
		"HTTP": 1,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_runtimeIntent_proto_enumTypes[1].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_runtimeIntent_proto_enumTypes[1]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_runtimeIntent_proto_rawDescGZIP(), []int{1}
}

// Results
type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg       string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	StateCode int64  `protobuf:"varint,2,opt,name=stateCode,proto3" json:"stateCode,omitempty"`
	Data      string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtimeIntent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeIntent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_runtimeIntent_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Result) GetStateCode() int64 {
	if x != nil {
		return x.StateCode
	}
	return 0
}

func (x *Result) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// APP状态
// 如果应用执行发生错误，或者产生其他的行为
// 则返回对应的StateCode，并在Msg中返回对应的结构化数据
// 调度框架会根据应用的生命周期，状态码以及状态信息，做出相应的处理
type APPStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg       string       `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	StateCode int64        `protobuf:"varint,2,opt,name=stateCode,proto3" json:"stateCode,omitempty"`
	Lifecycle AppLifecycle `protobuf:"varint,3,opt,name=lifecycle,proto3,enum=AppLifecycle" json:"lifecycle,omitempty"`
}

func (x *APPStatus) Reset() {
	*x = APPStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtimeIntent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APPStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APPStatus) ProtoMessage() {}

func (x *APPStatus) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeIntent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APPStatus.ProtoReflect.Descriptor instead.
func (*APPStatus) Descriptor() ([]byte, []int) {
	return file_runtimeIntent_proto_rawDescGZIP(), []int{1}
}

func (x *APPStatus) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *APPStatus) GetStateCode() int64 {
	if x != nil {
		return x.StateCode
	}
	return 0
}

func (x *APPStatus) GetLifecycle() AppLifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return AppLifecycle_INIT
}

// MetaData
type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type DataType `protobuf:"varint,2,opt,name=type,proto3,enum=DataType" json:"type,omitempty"`
	// 小数据直接传输，大数据需要应用通过URL/共享内存等方式同步
	Data string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtimeIntent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeIntent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_runtimeIntent_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Data) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_DATA
}

func (x *Data) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Intents
type InitIntent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 身份校验
	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
}

func (x *InitIntent) Reset() {
	*x = InitIntent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtimeIntent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitIntent) ProtoMessage() {}

func (x *InitIntent) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeIntent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitIntent.ProtoReflect.Descriptor instead.
func (*InitIntent) Descriptor() ([]byte, []int) {
	return file_runtimeIntent_proto_rawDescGZIP(), []int{3}
}

func (x *InitIntent) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

type StartIntent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"` //  repeated Data data=2;
}

func (x *StartIntent) Reset() {
	*x = StartIntent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtimeIntent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartIntent) ProtoMessage() {}

func (x *StartIntent) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeIntent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartIntent.ProtoReflect.Descriptor instead.
func (*StartIntent) Descriptor() ([]byte, []int) {
	return file_runtimeIntent_proto_rawDescGZIP(), []int{4}
}

func (x *StartIntent) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

type RestartIntent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"` //  repeated Data data=2;
}

func (x *RestartIntent) Reset() {
	*x = RestartIntent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtimeIntent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestartIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartIntent) ProtoMessage() {}

func (x *RestartIntent) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeIntent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartIntent.ProtoReflect.Descriptor instead.
func (*RestartIntent) Descriptor() ([]byte, []int) {
	return file_runtimeIntent_proto_rawDescGZIP(), []int{5}
}

func (x *RestartIntent) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

type StopIntent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"` //  repeated Data data=2;
}

func (x *StopIntent) Reset() {
	*x = StopIntent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtimeIntent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopIntent) ProtoMessage() {}

func (x *StopIntent) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeIntent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopIntent.ProtoReflect.Descriptor instead.
func (*StopIntent) Descriptor() ([]byte, []int) {
	return file_runtimeIntent_proto_rawDescGZIP(), []int{6}
}

func (x *StopIntent) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

type GetStatusIntent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
}

func (x *GetStatusIntent) Reset() {
	*x = GetStatusIntent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtimeIntent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusIntent) ProtoMessage() {}

func (x *GetStatusIntent) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeIntent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusIntent.ProtoReflect.Descriptor instead.
func (*GetStatusIntent) Descriptor() ([]byte, []int) {
	return file_runtimeIntent_proto_rawDescGZIP(), []int{7}
}

func (x *GetStatusIntent) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

type StoreIntent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	App  string  `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Data []*Data `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *StoreIntent) Reset() {
	*x = StoreIntent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtimeIntent_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreIntent) ProtoMessage() {}

func (x *StoreIntent) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeIntent_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreIntent.ProtoReflect.Descriptor instead.
func (*StoreIntent) Descriptor() ([]byte, []int) {
	return file_runtimeIntent_proto_rawDescGZIP(), []int{8}
}

func (x *StoreIntent) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *StoreIntent) GetData() []*Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type RestoreIntent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	App  string  `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Data []*Data `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *RestoreIntent) Reset() {
	*x = RestoreIntent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtimeIntent_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreIntent) ProtoMessage() {}

func (x *RestoreIntent) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeIntent_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreIntent.ProtoReflect.Descriptor instead.
func (*RestoreIntent) Descriptor() ([]byte, []int) {
	return file_runtimeIntent_proto_rawDescGZIP(), []int{9}
}

func (x *RestoreIntent) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *RestoreIntent) GetData() []*Data {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_runtimeIntent_proto protoreflect.FileDescriptor

var file_runtimeIntent_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x68, 0x0a, 0x09, 0x41, 0x50, 0x50, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x2b, 0x0a, 0x09, 0x6c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63,
	0x6c, 0x65, 0x52, 0x09, 0x6c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x22, 0x4d, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1e, 0x0a, 0x0a,
	0x49, 0x6e, 0x69, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x70, 0x22, 0x1f, 0x0a, 0x0b,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x70, 0x22, 0x21, 0x0a,
	0x0d, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x70,
	0x22, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x70, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x70,
	0x22, 0x23, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x61, 0x70, 0x70, 0x22, 0x3a, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x61, 0x70, 0x70, 0x12, 0x19, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x3c, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x61, 0x70, 0x70, 0x12, 0x19, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a,
	0x94, 0x01, 0x0a, 0x0c, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65,
	0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x49, 0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45,
	0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49,
	0x4e, 0x47, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45,
	0x44, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x54,
	0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41, 0x54, 0x45, 0x44, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x54, 0x4f, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x07, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x49, 0x47, 0x52,
	0x41, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x53, 0x54, 0x4f,
	0x52, 0x49, 0x4e, 0x47, 0x10, 0x09, 0x2a, 0x1e, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x41, 0x54, 0x41, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x48, 0x54, 0x54, 0x50, 0x10, 0x01, 0x32, 0x8c, 0x02, 0x0a, 0x0d, 0x52, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x69, 0x6e, 0x69, 0x74,
	0x12, 0x0b, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x07, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x20, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x12, 0x0c, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a,
	0x07, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x24, 0x0a, 0x07, 0x72, 0x65,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x0e, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00,
	0x12, 0x1e, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x12, 0x0b, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x49,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00,
	0x12, 0x2b, 0x0a, 0x09, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a,
	0x0a, 0x2e, 0x41, 0x50, 0x50, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x20, 0x0a,
	0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x0c, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x1a, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12,
	0x24, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x0e, 0x2e, 0x52, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x07, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_runtimeIntent_proto_rawDescOnce sync.Once
	file_runtimeIntent_proto_rawDescData = file_runtimeIntent_proto_rawDesc
)

func file_runtimeIntent_proto_rawDescGZIP() []byte {
	file_runtimeIntent_proto_rawDescOnce.Do(func() {
		file_runtimeIntent_proto_rawDescData = protoimpl.X.CompressGZIP(file_runtimeIntent_proto_rawDescData)
	})
	return file_runtimeIntent_proto_rawDescData
}

var file_runtimeIntent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_runtimeIntent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_runtimeIntent_proto_goTypes = []any{
	(AppLifecycle)(0),       // 0: AppLifecycle
	(DataType)(0),           // 1: DataType
	(*Result)(nil),          // 2: Result
	(*APPStatus)(nil),       // 3: APPStatus
	(*Data)(nil),            // 4: Data
	(*InitIntent)(nil),      // 5: InitIntent
	(*StartIntent)(nil),     // 6: StartIntent
	(*RestartIntent)(nil),   // 7: RestartIntent
	(*StopIntent)(nil),      // 8: StopIntent
	(*GetStatusIntent)(nil), // 9: GetStatusIntent
	(*StoreIntent)(nil),     // 10: StoreIntent
	(*RestoreIntent)(nil),   // 11: RestoreIntent
}
var file_runtimeIntent_proto_depIdxs = []int32{
	0,  // 0: APPStatus.lifecycle:type_name -> AppLifecycle
	1,  // 1: Data.type:type_name -> DataType
	4,  // 2: StoreIntent.data:type_name -> Data
	4,  // 3: RestoreIntent.data:type_name -> Data
	5,  // 4: RuntimeIntent.init:input_type -> InitIntent
	6,  // 5: RuntimeIntent.start:input_type -> StartIntent
	7,  // 6: RuntimeIntent.restart:input_type -> RestartIntent
	8,  // 7: RuntimeIntent.stop:input_type -> StopIntent
	9,  // 8: RuntimeIntent.getStatus:input_type -> GetStatusIntent
	10, // 9: RuntimeIntent.store:input_type -> StoreIntent
	11, // 10: RuntimeIntent.restore:input_type -> RestoreIntent
	2,  // 11: RuntimeIntent.init:output_type -> Result
	2,  // 12: RuntimeIntent.start:output_type -> Result
	2,  // 13: RuntimeIntent.restart:output_type -> Result
	2,  // 14: RuntimeIntent.stop:output_type -> Result
	3,  // 15: RuntimeIntent.getStatus:output_type -> APPStatus
	2,  // 16: RuntimeIntent.store:output_type -> Result
	2,  // 17: RuntimeIntent.restore:output_type -> Result
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_runtimeIntent_proto_init() }
func file_runtimeIntent_proto_init() {
	if File_runtimeIntent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_runtimeIntent_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtimeIntent_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*APPStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtimeIntent_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtimeIntent_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*InitIntent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtimeIntent_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*StartIntent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtimeIntent_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*RestartIntent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtimeIntent_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*StopIntent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtimeIntent_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetStatusIntent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtimeIntent_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*StoreIntent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtimeIntent_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*RestoreIntent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_runtimeIntent_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtimeIntent_proto_goTypes,
		DependencyIndexes: file_runtimeIntent_proto_depIdxs,
		EnumInfos:         file_runtimeIntent_proto_enumTypes,
		MessageInfos:      file_runtimeIntent_proto_msgTypes,
	}.Build()
	File_runtimeIntent_proto = out.File
	file_runtimeIntent_proto_rawDesc = nil
	file_runtimeIntent_proto_goTypes = nil
	file_runtimeIntent_proto_depIdxs = nil
}
