syntax = "proto3";

option java_multiple_files = true;
option java_package = "edu.hit.wasm_interface";
option java_outer_classname = "WasmInterfaceProto";
option go_package = ".;wasm_interface";
package wasm_interface;

service WasmInterface {
    // runtime service
    rpc deploy (DeployIntent) returns (Result) {}

    // task service
    rpc init (InitIntent) returns (Result) {}
    rpc start (StartIntent) returns (Result) {}

    // 释放资源
    rpc destroy (DestroyIntent) returns (Result) {}
    
    // 获取应用状态
    rpc getStatus (GetStatusIntent) returns (APPStatus) {}

    // 迁移相关
    rpc store (StoreIntent) returns (Result) {}
    rpc restore (RestoreIntent) returns (Result) {}
}

// Constants
// 应用生命周期
 enum AppLifecycle {
    INIT = 0;
    PENDING = 1;
    RUNNING = 2;
    COMPLETED = 3;
    ERROR = 4;
}

// 应用数据类型
enum DataType {
    DATA = 0;
    HTTP = 1;
    // ... 其他数据格式
}

// Results
message Result {
	int32 stateCode = 1;
    string msg = 2;
	optional Data data = 3;
}

// 如果应用执行发生错误，或者产生其他的行为
// 则返回对应的StateCode，并在Msg中返回对应的结构化数据
// 调度框架会根据应用的生命周期，状态码以及状态信息，做出相应的处理
message APPStatus {
    string msg = 1;
    int32 stateCode = 2;
    AppLifecycle lifecycle = 3;
}

// MetaData
message Data {
    DataType type = 1;
    // 小数据直接传输，大数据需要应用通过URL/共享内存等方式同步
    bytes data = 2;
}

// 运行时配置
message RuntimeConfig{
    optional string aot_compiler = 1;
    repeated string aot_compiler_args = 2;
    enum ForceLinkage {
        Address=0;
        FuncRef=1;
    } 
    optional ForceLinkage force_linkage = 3;
    optional uint32 stack_size = 4;
}

// 部署信息
message Deploy{
    // 应用名称
    string app = 1;
    // 运行时配置
    optional RuntimeConfig runtime_config = 2;
    // 应用包含的所有wasm文件,请按照实例化的顺序传输wasm文件
    repeated WasmFile wasm = 4; 
    // 应用程序执行所依赖的资源
    repeated Resource resource = 5;
}

message WasmFile{
	// wasm module的名字
	string name = 1;
	// 二进制格式的wasm文件
    Data data = 2;
}

message Resource{
	// 资源名称
	string name = 1;
    // 资源内容
	Data data = 2;
}

// Intents
message DeployIntent {
    // 身份校验
    string identity = 1;
    // 每个data都是一个应用，一个应用可能包含多个wasm文件
    repeated Deploy data = 2;
}

message InitIntent {
    // 应用名称
    string app = 1;
}

message StartIntent {
    // 应用名称
    string app = 1;
}

message DestroyIntent {
    // 应用名称
    string app = 1;
}

message GetStatusIntent {
    // 应用名称
    string app = 1;
}

message StoreIntent {
    // 应用名称
    string app = 1;
}

message RestoreIntent {
    // 应用名称
    string app = 1;
    // 恢复的状态
    Data data = 2;
}