// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: wasm_interface.proto

package wasm_interface

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WasmInterfaceClient is the client API for WasmInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WasmInterfaceClient interface {
	// runtime service
	Deploy(ctx context.Context, in *DeployIntent, opts ...grpc.CallOption) (*Result, error)
	// task service
	Init(ctx context.Context, in *InitIntent, opts ...grpc.CallOption) (*Result, error)
	Start(ctx context.Context, in *StartIntent, opts ...grpc.CallOption) (*Result, error)
	// 释放资源
	Destroy(ctx context.Context, in *DestroyIntent, opts ...grpc.CallOption) (*Result, error)
	// 获取应用状态，调用方需要对每个执行的任务都获取一次状态
	GetStatus(ctx context.Context, in *GetStatusIntent, opts ...grpc.CallOption) (*Result, error)
	// 迁移相关
	Store(ctx context.Context, in *StoreIntent, opts ...grpc.CallOption) (*Result, error)
	Restore(ctx context.Context, in *RestoreIntent, opts ...grpc.CallOption) (*Result, error)
}

type wasmInterfaceClient struct {
	cc grpc.ClientConnInterface
}

func NewWasmInterfaceClient(cc grpc.ClientConnInterface) WasmInterfaceClient {
	return &wasmInterfaceClient{cc}
}

func (c *wasmInterfaceClient) Deploy(ctx context.Context, in *DeployIntent, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/wasm_interface.WasmInterface/deploy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wasmInterfaceClient) Init(ctx context.Context, in *InitIntent, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/wasm_interface.WasmInterface/init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wasmInterfaceClient) Start(ctx context.Context, in *StartIntent, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/wasm_interface.WasmInterface/start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wasmInterfaceClient) Destroy(ctx context.Context, in *DestroyIntent, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/wasm_interface.WasmInterface/destroy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wasmInterfaceClient) GetStatus(ctx context.Context, in *GetStatusIntent, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/wasm_interface.WasmInterface/getStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wasmInterfaceClient) Store(ctx context.Context, in *StoreIntent, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/wasm_interface.WasmInterface/store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wasmInterfaceClient) Restore(ctx context.Context, in *RestoreIntent, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/wasm_interface.WasmInterface/restore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WasmInterfaceServer is the server API for WasmInterface service.
// All implementations must embed UnimplementedWasmInterfaceServer
// for forward compatibility
type WasmInterfaceServer interface {
	// runtime service
	Deploy(context.Context, *DeployIntent) (*Result, error)
	// task service
	Init(context.Context, *InitIntent) (*Result, error)
	Start(context.Context, *StartIntent) (*Result, error)
	// 释放资源
	Destroy(context.Context, *DestroyIntent) (*Result, error)
	// 获取应用状态，调用方需要对每个执行的任务都获取一次状态
	GetStatus(context.Context, *GetStatusIntent) (*Result, error)
	// 迁移相关
	Store(context.Context, *StoreIntent) (*Result, error)
	Restore(context.Context, *RestoreIntent) (*Result, error)
	mustEmbedUnimplementedWasmInterfaceServer()
}

// UnimplementedWasmInterfaceServer must be embedded to have forward compatible implementations.
type UnimplementedWasmInterfaceServer struct {
}

func (UnimplementedWasmInterfaceServer) Deploy(context.Context, *DeployIntent) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deploy not implemented")
}
func (UnimplementedWasmInterfaceServer) Init(context.Context, *InitIntent) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedWasmInterfaceServer) Start(context.Context, *StartIntent) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedWasmInterfaceServer) Destroy(context.Context, *DestroyIntent) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedWasmInterfaceServer) GetStatus(context.Context, *GetStatusIntent) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedWasmInterfaceServer) Store(context.Context, *StoreIntent) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedWasmInterfaceServer) Restore(context.Context, *RestoreIntent) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedWasmInterfaceServer) mustEmbedUnimplementedWasmInterfaceServer() {}

// UnsafeWasmInterfaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WasmInterfaceServer will
// result in compilation errors.
type UnsafeWasmInterfaceServer interface {
	mustEmbedUnimplementedWasmInterfaceServer()
}

func RegisterWasmInterfaceServer(s grpc.ServiceRegistrar, srv WasmInterfaceServer) {
	s.RegisterService(&WasmInterface_ServiceDesc, srv)
}

func _WasmInterface_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployIntent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WasmInterfaceServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wasm_interface.WasmInterface/deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WasmInterfaceServer).Deploy(ctx, req.(*DeployIntent))
	}
	return interceptor(ctx, in, info, handler)
}

func _WasmInterface_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitIntent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WasmInterfaceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wasm_interface.WasmInterface/init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WasmInterfaceServer).Init(ctx, req.(*InitIntent))
	}
	return interceptor(ctx, in, info, handler)
}

func _WasmInterface_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartIntent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WasmInterfaceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wasm_interface.WasmInterface/start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WasmInterfaceServer).Start(ctx, req.(*StartIntent))
	}
	return interceptor(ctx, in, info, handler)
}

func _WasmInterface_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyIntent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WasmInterfaceServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wasm_interface.WasmInterface/destroy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WasmInterfaceServer).Destroy(ctx, req.(*DestroyIntent))
	}
	return interceptor(ctx, in, info, handler)
}

func _WasmInterface_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusIntent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WasmInterfaceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wasm_interface.WasmInterface/getStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WasmInterfaceServer).GetStatus(ctx, req.(*GetStatusIntent))
	}
	return interceptor(ctx, in, info, handler)
}

func _WasmInterface_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreIntent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WasmInterfaceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wasm_interface.WasmInterface/store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WasmInterfaceServer).Store(ctx, req.(*StoreIntent))
	}
	return interceptor(ctx, in, info, handler)
}

func _WasmInterface_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreIntent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WasmInterfaceServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wasm_interface.WasmInterface/restore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WasmInterfaceServer).Restore(ctx, req.(*RestoreIntent))
	}
	return interceptor(ctx, in, info, handler)
}

// WasmInterface_ServiceDesc is the grpc.ServiceDesc for WasmInterface service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WasmInterface_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wasm_interface.WasmInterface",
	HandlerType: (*WasmInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "deploy",
			Handler:    _WasmInterface_Deploy_Handler,
		},
		{
			MethodName: "init",
			Handler:    _WasmInterface_Init_Handler,
		},
		{
			MethodName: "start",
			Handler:    _WasmInterface_Start_Handler,
		},
		{
			MethodName: "destroy",
			Handler:    _WasmInterface_Destroy_Handler,
		},
		{
			MethodName: "getStatus",
			Handler:    _WasmInterface_GetStatus_Handler,
		},
		{
			MethodName: "store",
			Handler:    _WasmInterface_Store_Handler,
		},
		{
			MethodName: "restore",
			Handler:    _WasmInterface_Restore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wasm_interface.proto",
}
