// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: wasm_interface.proto

package wasm_interface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Constants
// 应用生命周期
type AppLifecycle int32

const (
	AppLifecycle_INIT      AppLifecycle = 0
	AppLifecycle_PENDING   AppLifecycle = 1
	AppLifecycle_RUNNING   AppLifecycle = 2
	AppLifecycle_COMPLETED AppLifecycle = 3
	AppLifecycle_ERROR     AppLifecycle = 4
)

// Enum value maps for AppLifecycle.
var (
	AppLifecycle_name = map[int32]string{
		0: "INIT",
		1: "PENDING",
		2: "RUNNING",
		3: "COMPLETED",
		4: "ERROR",
	}
	AppLifecycle_value = map[string]int32{
		"INIT":      0,
		"PENDING":   1,
		"RUNNING":   2,
		"COMPLETED": 3,
		"ERROR":     4,
	}
)

func (x AppLifecycle) Enum() *AppLifecycle {
	p := new(AppLifecycle)
	*p = x
	return p
}

func (x AppLifecycle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppLifecycle) Descriptor() protoreflect.EnumDescriptor {
	return file_wasm_interface_proto_enumTypes[0].Descriptor()
}

func (AppLifecycle) Type() protoreflect.EnumType {
	return &file_wasm_interface_proto_enumTypes[0]
}

func (x AppLifecycle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppLifecycle.Descriptor instead.
func (AppLifecycle) EnumDescriptor() ([]byte, []int) {
	return file_wasm_interface_proto_rawDescGZIP(), []int{0}
}

// 应用数据类型
type DataType int32

const (
	DataType_DATA DataType = 0
	DataType_HTTP DataType = 1 // ... 其他数据格式
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "DATA",
		1: "HTTP",
	}
	DataType_value = map[string]int32{
		"DATA": 0,
		"HTTP": 1,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_wasm_interface_proto_enumTypes[1].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_wasm_interface_proto_enumTypes[1]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_wasm_interface_proto_rawDescGZIP(), []int{1}
}

type RuntimeConfig_ForceLinkage int32

const (
	RuntimeConfig_Address RuntimeConfig_ForceLinkage = 0
	RuntimeConfig_FuncRef RuntimeConfig_ForceLinkage = 1
)

// Enum value maps for RuntimeConfig_ForceLinkage.
var (
	RuntimeConfig_ForceLinkage_name = map[int32]string{
		0: "Address",
		1: "FuncRef",
	}
	RuntimeConfig_ForceLinkage_value = map[string]int32{
		"Address": 0,
		"FuncRef": 1,
	}
)

func (x RuntimeConfig_ForceLinkage) Enum() *RuntimeConfig_ForceLinkage {
	p := new(RuntimeConfig_ForceLinkage)
	*p = x
	return p
}

func (x RuntimeConfig_ForceLinkage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeConfig_ForceLinkage) Descriptor() protoreflect.EnumDescriptor {
	return file_wasm_interface_proto_enumTypes[2].Descriptor()
}

func (RuntimeConfig_ForceLinkage) Type() protoreflect.EnumType {
	return &file_wasm_interface_proto_enumTypes[2]
}

func (x RuntimeConfig_ForceLinkage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeConfig_ForceLinkage.Descriptor instead.
func (RuntimeConfig_ForceLinkage) EnumDescriptor() ([]byte, []int) {
	return file_wasm_interface_proto_rawDescGZIP(), []int{3, 0}
}

// Results
type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateCode int32  `protobuf:"varint,1,opt,name=stateCode,proto3" json:"stateCode,omitempty"`
	Msg       string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data      *Data  `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wasm_interface_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_wasm_interface_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_wasm_interface_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetStateCode() int32 {
	if x != nil {
		return x.StateCode
	}
	return 0
}

func (x *Result) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Result) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// 如果应用执行发生错误，或者产生其他的行为
// 则返回对应的StateCode，并在Msg中返回对应的结构化数据
// 调度框架会根据应用的生命周期，状态码以及状态信息，做出相应的处理
type APPStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg       string       `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	StateCode int32        `protobuf:"varint,2,opt,name=stateCode,proto3" json:"stateCode,omitempty"`
	Lifecycle AppLifecycle `protobuf:"varint,3,opt,name=lifecycle,proto3,enum=wasm_interface.AppLifecycle" json:"lifecycle,omitempty"`
}

func (x *APPStatus) Reset() {
	*x = APPStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wasm_interface_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APPStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APPStatus) ProtoMessage() {}

func (x *APPStatus) ProtoReflect() protoreflect.Message {
	mi := &file_wasm_interface_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APPStatus.ProtoReflect.Descriptor instead.
func (*APPStatus) Descriptor() ([]byte, []int) {
	return file_wasm_interface_proto_rawDescGZIP(), []int{1}
}

func (x *APPStatus) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *APPStatus) GetStateCode() int32 {
	if x != nil {
		return x.StateCode
	}
	return 0
}

func (x *APPStatus) GetLifecycle() AppLifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return AppLifecycle_INIT
}

// MetaData
type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type DataType `protobuf:"varint,1,opt,name=type,proto3,enum=wasm_interface.DataType" json:"type,omitempty"`
	// 小数据直接传输，大数据需要应用通过URL/共享内存等方式同步
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wasm_interface_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_wasm_interface_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_wasm_interface_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_DATA
}

func (x *Data) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 运行时配置
type RuntimeConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AotCompiler     *string                     `protobuf:"bytes,1,opt,name=aot_compiler,json=aotCompiler,proto3,oneof" json:"aot_compiler,omitempty"`
	AotCompilerArgs []string                    `protobuf:"bytes,2,rep,name=aot_compiler_args,json=aotCompilerArgs,proto3" json:"aot_compiler_args,omitempty"`
	ForceLinkage    *RuntimeConfig_ForceLinkage `protobuf:"varint,3,opt,name=force_linkage,json=forceLinkage,proto3,enum=wasm_interface.RuntimeConfig_ForceLinkage,oneof" json:"force_linkage,omitempty"`
	StackSize       *uint32                     `protobuf:"varint,4,opt,name=stack_size,json=stackSize,proto3,oneof" json:"stack_size,omitempty"`
}

func (x *RuntimeConfig) Reset() {
	*x = RuntimeConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wasm_interface_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeConfig) ProtoMessage() {}

func (x *RuntimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_wasm_interface_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeConfig.ProtoReflect.Descriptor instead.
func (*RuntimeConfig) Descriptor() ([]byte, []int) {
	return file_wasm_interface_proto_rawDescGZIP(), []int{3}
}

func (x *RuntimeConfig) GetAotCompiler() string {
	if x != nil && x.AotCompiler != nil {
		return *x.AotCompiler
	}
	return ""
}

func (x *RuntimeConfig) GetAotCompilerArgs() []string {
	if x != nil {
		return x.AotCompilerArgs
	}
	return nil
}

func (x *RuntimeConfig) GetForceLinkage() RuntimeConfig_ForceLinkage {
	if x != nil && x.ForceLinkage != nil {
		return *x.ForceLinkage
	}
	return RuntimeConfig_Address
}

func (x *RuntimeConfig) GetStackSize() uint32 {
	if x != nil && x.StackSize != nil {
		return *x.StackSize
	}
	return 0
}

// 部署信息
type Deploy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 应用名称
	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// 运行时配置
	RuntimeConfig *RuntimeConfig `protobuf:"bytes,2,opt,name=runtime_config,json=runtimeConfig,proto3,oneof" json:"runtime_config,omitempty"`
	// 应用包含的所有wasm文件,请按照实例化的顺序传输wasm文件
	Wasm []*WasmFile `protobuf:"bytes,4,rep,name=wasm,proto3" json:"wasm,omitempty"`
	// 应用程序执行所依赖的资源
	Resource []*Resource `protobuf:"bytes,5,rep,name=resource,proto3" json:"resource,omitempty"`
}

func (x *Deploy) Reset() {
	*x = Deploy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wasm_interface_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deploy) ProtoMessage() {}

func (x *Deploy) ProtoReflect() protoreflect.Message {
	mi := &file_wasm_interface_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deploy.ProtoReflect.Descriptor instead.
func (*Deploy) Descriptor() ([]byte, []int) {
	return file_wasm_interface_proto_rawDescGZIP(), []int{4}
}

func (x *Deploy) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *Deploy) GetRuntimeConfig() *RuntimeConfig {
	if x != nil {
		return x.RuntimeConfig
	}
	return nil
}

func (x *Deploy) GetWasm() []*WasmFile {
	if x != nil {
		return x.Wasm
	}
	return nil
}

func (x *Deploy) GetResource() []*Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type WasmFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// wasm module的名字
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 二进制格式的wasm文件
	Data *Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *WasmFile) Reset() {
	*x = WasmFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wasm_interface_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WasmFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmFile) ProtoMessage() {}

func (x *WasmFile) ProtoReflect() protoreflect.Message {
	mi := &file_wasm_interface_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmFile.ProtoReflect.Descriptor instead.
func (*WasmFile) Descriptor() ([]byte, []int) {
	return file_wasm_interface_proto_rawDescGZIP(), []int{5}
}

func (x *WasmFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WasmFile) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 资源名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 资源内容
	Data *Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Resource) Reset() {
	*x = Resource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wasm_interface_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_wasm_interface_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_wasm_interface_proto_rawDescGZIP(), []int{6}
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// Intents
type DeployIntent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 身份校验
	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// 每个data都是一个应用，一个应用可能包含多个wasm文件
	Data []*Deploy `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *DeployIntent) Reset() {
	*x = DeployIntent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wasm_interface_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployIntent) ProtoMessage() {}

func (x *DeployIntent) ProtoReflect() protoreflect.Message {
	mi := &file_wasm_interface_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployIntent.ProtoReflect.Descriptor instead.
func (*DeployIntent) Descriptor() ([]byte, []int) {
	return file_wasm_interface_proto_rawDescGZIP(), []int{7}
}

func (x *DeployIntent) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *DeployIntent) GetData() []*Deploy {
	if x != nil {
		return x.Data
	}
	return nil
}

type InitIntent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 应用名称
	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
}

func (x *InitIntent) Reset() {
	*x = InitIntent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wasm_interface_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitIntent) ProtoMessage() {}

func (x *InitIntent) ProtoReflect() protoreflect.Message {
	mi := &file_wasm_interface_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitIntent.ProtoReflect.Descriptor instead.
func (*InitIntent) Descriptor() ([]byte, []int) {
	return file_wasm_interface_proto_rawDescGZIP(), []int{8}
}

func (x *InitIntent) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

type StartIntent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 应用名称
	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
}

func (x *StartIntent) Reset() {
	*x = StartIntent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wasm_interface_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartIntent) ProtoMessage() {}

func (x *StartIntent) ProtoReflect() protoreflect.Message {
	mi := &file_wasm_interface_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartIntent.ProtoReflect.Descriptor instead.
func (*StartIntent) Descriptor() ([]byte, []int) {
	return file_wasm_interface_proto_rawDescGZIP(), []int{9}
}

func (x *StartIntent) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

type DestroyIntent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 应用名称
	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
}

func (x *DestroyIntent) Reset() {
	*x = DestroyIntent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wasm_interface_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyIntent) ProtoMessage() {}

func (x *DestroyIntent) ProtoReflect() protoreflect.Message {
	mi := &file_wasm_interface_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyIntent.ProtoReflect.Descriptor instead.
func (*DestroyIntent) Descriptor() ([]byte, []int) {
	return file_wasm_interface_proto_rawDescGZIP(), []int{10}
}

func (x *DestroyIntent) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

type GetStatusIntent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 应用名称
	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
}

func (x *GetStatusIntent) Reset() {
	*x = GetStatusIntent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wasm_interface_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusIntent) ProtoMessage() {}

func (x *GetStatusIntent) ProtoReflect() protoreflect.Message {
	mi := &file_wasm_interface_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusIntent.ProtoReflect.Descriptor instead.
func (*GetStatusIntent) Descriptor() ([]byte, []int) {
	return file_wasm_interface_proto_rawDescGZIP(), []int{11}
}

func (x *GetStatusIntent) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

type StoreIntent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 应用名称
	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
}

func (x *StoreIntent) Reset() {
	*x = StoreIntent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wasm_interface_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreIntent) ProtoMessage() {}

func (x *StoreIntent) ProtoReflect() protoreflect.Message {
	mi := &file_wasm_interface_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreIntent.ProtoReflect.Descriptor instead.
func (*StoreIntent) Descriptor() ([]byte, []int) {
	return file_wasm_interface_proto_rawDescGZIP(), []int{12}
}

func (x *StoreIntent) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

type RestoreIntent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 应用名称
	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// 恢复的状态
	Data *Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RestoreIntent) Reset() {
	*x = RestoreIntent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wasm_interface_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreIntent) ProtoMessage() {}

func (x *RestoreIntent) ProtoReflect() protoreflect.Message {
	mi := &file_wasm_interface_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreIntent.ProtoReflect.Descriptor instead.
func (*RestoreIntent) Descriptor() ([]byte, []int) {
	return file_wasm_interface_proto_rawDescGZIP(), []int{13}
}

func (x *RestoreIntent) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *RestoreIntent) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_wasm_interface_proto protoreflect.FileDescriptor

var file_wasm_interface_proto_rawDesc = []byte{
	0x0a, 0x14, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x22, 0x70, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x12, 0x2d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42,
	0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x77, 0x0a, 0x09, 0x41, 0x50, 0x50, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x6c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x66,
	0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x52, 0x09, 0x6c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c,
	0x65, 0x22, 0x48, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xb9, 0x02, 0x0a, 0x0d,
	0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x26, 0x0a,
	0x0c, 0x61, 0x6f, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x2a, 0x0a, 0x11, 0x61, 0x6f, 0x74, 0x5f, 0x63, 0x6f, 0x6d,
	0x70, 0x69, 0x6c, 0x65, 0x72, 0x5f, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0f, 0x61, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x41, 0x72, 0x67,
	0x73, 0x12, 0x54, 0x0a, 0x0d, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x6e,
	0x6b, 0x61, 0x67, 0x65, 0x48, 0x01, 0x52, 0x0c, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x6e,
	0x6b, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x63, 0x6b,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x02, 0x52, 0x09, 0x73,
	0x74, 0x61, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x88, 0x01, 0x01, 0x22, 0x28, 0x0a, 0x0c, 0x46,
	0x6f, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x75, 0x6e, 0x63,
	0x52, 0x65, 0x66, 0x10, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x61, 0x6f, 0x74, 0x5f, 0x63, 0x6f,
	0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x66, 0x6f, 0x72, 0x63, 0x65,
	0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x67, 0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x73, 0x74, 0x61,
	0x63, 0x6b, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x22, 0xdc, 0x01, 0x0a, 0x06, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x61, 0x70, 0x70, 0x12, 0x49, 0x0a, 0x0e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x77,
	0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x52, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x0d, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x88, 0x01, 0x01, 0x12,
	0x2c, 0x0a, 0x04, 0x77, 0x61, 0x73, 0x6d, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x57,
	0x61, 0x73, 0x6d, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x77, 0x61, 0x73, 0x6d, 0x12, 0x34, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x48, 0x0a, 0x08, 0x57, 0x61, 0x73, 0x6d, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x48, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x56, 0x0a, 0x0c, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x69, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61,
	0x70, 0x70, 0x22, 0x1f, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x61, 0x70, 0x70, 0x22, 0x21, 0x0a, 0x0d, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x49, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x61, 0x70, 0x70, 0x22, 0x23, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x70, 0x22, 0x1f, 0x0a, 0x0b, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x70, 0x22, 0x4b, 0x0a, 0x0d,
	0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x70, 0x12,
	0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x4c, 0x0a, 0x0c, 0x41, 0x70, 0x70,
	0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x49,
	0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0d, 0x0a,
	0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x2a, 0x1e, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x41, 0x54, 0x41, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x48, 0x54, 0x54, 0x50, 0x10, 0x01, 0x32, 0xe2, 0x03, 0x0a, 0x0d, 0x57, 0x61, 0x73, 0x6d,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x06, 0x64, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x12, 0x1c, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x49, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x1a, 0x16, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x04, 0x69,
	0x6e, 0x69, 0x74, 0x12, 0x1a, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a,
	0x16, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x1b, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a,
	0x16, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x07, 0x64, 0x65, 0x73,
	0x74, 0x72, 0x6f, 0x79, 0x12, 0x1d, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x49, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x1a, 0x16, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x49, 0x0a,
	0x09, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x2e, 0x77, 0x61, 0x73,
	0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x19, 0x2e, 0x77, 0x61,
	0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x41, 0x50, 0x50,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x12, 0x1b, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x16,
	0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x12, 0x1d, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x1a, 0x16, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x40, 0x0a, 0x16,
	0x65, 0x64, 0x75, 0x2e, 0x68, 0x69, 0x74, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x42, 0x12, 0x57, 0x61, 0x73, 0x6d, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x10, 0x2e, 0x3b,
	0x77, 0x61, 0x73, 0x6d, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wasm_interface_proto_rawDescOnce sync.Once
	file_wasm_interface_proto_rawDescData = file_wasm_interface_proto_rawDesc
)

func file_wasm_interface_proto_rawDescGZIP() []byte {
	file_wasm_interface_proto_rawDescOnce.Do(func() {
		file_wasm_interface_proto_rawDescData = protoimpl.X.CompressGZIP(file_wasm_interface_proto_rawDescData)
	})
	return file_wasm_interface_proto_rawDescData
}

var file_wasm_interface_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_wasm_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_wasm_interface_proto_goTypes = []interface{}{
	(AppLifecycle)(0),               // 0: wasm_interface.AppLifecycle
	(DataType)(0),                   // 1: wasm_interface.DataType
	(RuntimeConfig_ForceLinkage)(0), // 2: wasm_interface.RuntimeConfig.ForceLinkage
	(*Result)(nil),                  // 3: wasm_interface.Result
	(*APPStatus)(nil),               // 4: wasm_interface.APPStatus
	(*Data)(nil),                    // 5: wasm_interface.Data
	(*RuntimeConfig)(nil),           // 6: wasm_interface.RuntimeConfig
	(*Deploy)(nil),                  // 7: wasm_interface.Deploy
	(*WasmFile)(nil),                // 8: wasm_interface.WasmFile
	(*Resource)(nil),                // 9: wasm_interface.Resource
	(*DeployIntent)(nil),            // 10: wasm_interface.DeployIntent
	(*InitIntent)(nil),              // 11: wasm_interface.InitIntent
	(*StartIntent)(nil),             // 12: wasm_interface.StartIntent
	(*DestroyIntent)(nil),           // 13: wasm_interface.DestroyIntent
	(*GetStatusIntent)(nil),         // 14: wasm_interface.GetStatusIntent
	(*StoreIntent)(nil),             // 15: wasm_interface.StoreIntent
	(*RestoreIntent)(nil),           // 16: wasm_interface.RestoreIntent
}
var file_wasm_interface_proto_depIdxs = []int32{
	5,  // 0: wasm_interface.Result.data:type_name -> wasm_interface.Data
	0,  // 1: wasm_interface.APPStatus.lifecycle:type_name -> wasm_interface.AppLifecycle
	1,  // 2: wasm_interface.Data.type:type_name -> wasm_interface.DataType
	2,  // 3: wasm_interface.RuntimeConfig.force_linkage:type_name -> wasm_interface.RuntimeConfig.ForceLinkage
	6,  // 4: wasm_interface.Deploy.runtime_config:type_name -> wasm_interface.RuntimeConfig
	8,  // 5: wasm_interface.Deploy.wasm:type_name -> wasm_interface.WasmFile
	9,  // 6: wasm_interface.Deploy.resource:type_name -> wasm_interface.Resource
	5,  // 7: wasm_interface.WasmFile.data:type_name -> wasm_interface.Data
	5,  // 8: wasm_interface.Resource.data:type_name -> wasm_interface.Data
	7,  // 9: wasm_interface.DeployIntent.data:type_name -> wasm_interface.Deploy
	5,  // 10: wasm_interface.RestoreIntent.data:type_name -> wasm_interface.Data
	10, // 11: wasm_interface.WasmInterface.deploy:input_type -> wasm_interface.DeployIntent
	11, // 12: wasm_interface.WasmInterface.init:input_type -> wasm_interface.InitIntent
	12, // 13: wasm_interface.WasmInterface.start:input_type -> wasm_interface.StartIntent
	13, // 14: wasm_interface.WasmInterface.destroy:input_type -> wasm_interface.DestroyIntent
	14, // 15: wasm_interface.WasmInterface.getStatus:input_type -> wasm_interface.GetStatusIntent
	15, // 16: wasm_interface.WasmInterface.store:input_type -> wasm_interface.StoreIntent
	16, // 17: wasm_interface.WasmInterface.restore:input_type -> wasm_interface.RestoreIntent
	3,  // 18: wasm_interface.WasmInterface.deploy:output_type -> wasm_interface.Result
	3,  // 19: wasm_interface.WasmInterface.init:output_type -> wasm_interface.Result
	3,  // 20: wasm_interface.WasmInterface.start:output_type -> wasm_interface.Result
	3,  // 21: wasm_interface.WasmInterface.destroy:output_type -> wasm_interface.Result
	4,  // 22: wasm_interface.WasmInterface.getStatus:output_type -> wasm_interface.APPStatus
	3,  // 23: wasm_interface.WasmInterface.store:output_type -> wasm_interface.Result
	3,  // 24: wasm_interface.WasmInterface.restore:output_type -> wasm_interface.Result
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_wasm_interface_proto_init() }
func file_wasm_interface_proto_init() {
	if File_wasm_interface_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wasm_interface_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wasm_interface_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APPStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wasm_interface_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wasm_interface_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wasm_interface_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deploy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wasm_interface_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WasmFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wasm_interface_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wasm_interface_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployIntent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wasm_interface_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitIntent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wasm_interface_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartIntent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wasm_interface_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyIntent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wasm_interface_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatusIntent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wasm_interface_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreIntent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wasm_interface_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreIntent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_wasm_interface_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_wasm_interface_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_wasm_interface_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wasm_interface_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wasm_interface_proto_goTypes,
		DependencyIndexes: file_wasm_interface_proto_depIdxs,
		EnumInfos:         file_wasm_interface_proto_enumTypes,
		MessageInfos:      file_wasm_interface_proto_msgTypes,
	}.Build()
	File_wasm_interface_proto = out.File
	file_wasm_interface_proto_rawDesc = nil
	file_wasm_interface_proto_goTypes = nil
	file_wasm_interface_proto_depIdxs = nil
}
